/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vw_learner_VWFloatLearner */

#ifndef _Included_vw_learner_VWFloatLearner
#define _Included_vw_learner_VWFloatLearner
#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT jfloat JNICALL Java_vw_learner_VWFloatLearner_predict
(JNIEnv *, jobject, jstring, jboolean, jlong);

JNIEXPORT jfloat JNICALL Java_vw_learner_VWLearners_getWeight
(JNIEnv *, jobject, jlong, jint, jint);

JNIEXPORT void JNICALL Java_vw_learner_VWLearners_setWeight
(JNIEnv *, jobject, jlong, jint, jint, jfloat);

#ifdef __cplusplus
}
#endif
#endif
